### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by decwodie** [massedge/wordpress-plugin-export-media-library#29]
I installed the plugin, went to Media/Export and ran the export but it only opened a new tab in the browser and nothing else happened. PHP version is 7.3.2

**Comment by decwodie** [comment]
PHP Version is 7.3.2

**Comment by andrejpavlovic** [comment]
Can I get the WordPress version info as well as who is your hosting provider? I guess you don't see any errors anywhere?

**Comment by decwodie** [comment]
WordPress 5.4

Ipage.com hosting

 

No, it just opens a blank tab (about:blank), spins for a bit then stops. Nothing else happens.

**Comment by andrejpavlovic** [comment]
Can you see if you get get the error logs by following instructions here: https://www.ipage.com/help/article/website-errors-500-internal-server-error

**Comment by decwodie** [comment]
The most recent date in the log is 2017

**Comment by andrejpavlovic** [comment]
Hmm, that doesn't give me much to go on. I reached out to ipage.com to see if I can get a test account setup in order to reproduce the issue, but seems like that's not possible. Not sure what else to do.

**Comment by decwodie** [comment]
Should I uninstall and reinstall the plugin? I can also deactivate other plugins to test.

**Comment by decwodie** [comment]
Why does it open a blank tab in the browser?

**Comment by decwodie** [comment]
Also, sorry for the emails, but can I get what you need in the ipage account?

**Comment by andrejpavlovic** [comment]
> Should I uninstall and reinstall the plugin? I can also deactivate other plugins to test.

Installing/uninstalling probably won’t be of much use. You could try disabling all other plugins and then trying to export again.

>Why does it open a blank tab in the browser?

The new tab opens in the browser in order to start the download. Once the download starts, the tab would disappear (or if it was working properly it, you wouldn’t see the tab at all).

>Also, sorry for the emails, but can I get what you need in the ipage account?

The main thing that could help is if I could see the issue for myself and try to troubleshoot it. That’s why I wanted to setup a separate installation of WordPress and try out the plugin on its own. If you can setup a separate WordPress instance and try the plugin on its own that would be best.

**Comment by decwodie** [comment]
I have a test site we can use – I assume you need access to the wordpress dashboard?

**Comment by decwodie** [comment]
AHA! It works in the test site! It opens the tab and starts the download.

**Comment by andrejpavlovic** [comment]
Well that's good news! Hopefully it's just a conflict with one of the other plugins then. If it's not that, we might have to dig deeper...

**Comment by decwodie** [comment]
I reinstalled in the original site and turned off all other plugins. No love. Do you want access in the Wordpress dashboard to troubleshoot?

**Comment by andrejpavlovic** [comment]
Issue has become stale. Please reopen if further assistance needed.
