### ISSUE TITLE
File Decompression Failed

### ISSUE THREAD

**Issue by Macphot** [massedge/wordpress-plugin-export-media-library#30]
Keep getting this message when I try to unzip the downloaded compressed media library file.
I've tried all different options when creating the zip file and used a couple of different apps to unzip.

**Comment by Macphot** [comment]
Hi, thanks for your response.
The file is about 1.2Gb and I’ve used the default Mac unzipper and FileZilla.
I’ll give 7-zip a go cheers

**Comment by Macphot** [comment]
I see 7-Zip is only available for PC - I'm on a Mac
    On Thursday, 23 April 2020, 15:13:46 BST, Darren Macdonald <mailmacaway@yahoo.co.uk> wrote:  
 
 Hi, thanks for your response.The file is about 1.2Gb and I’ve used the default Mac unzipper and FileZilla.I’ll give 7-zip a go cheers

Sent from my iPhone

On 23 Apr 2020, at 14:41, Andrej Pavlovic <notifications@github.com> wrote:



﻿


How big is the file?
Which program are you using to unzip?
If all else fails, try using 7-zip to decompress the file.

**Comment by andrejpavlovic** [comment]
Sorry I forgot. You can try [keka](https://www.keka.io/), that's worked for me in the past.

The other thing to check is whether the archive was fully downloaded or stopped before finishing. Try downloading the file again, and see if there is a difference in size of the zip file.  It could be that the entire export never gets fully downloaded and that's why it appears corrupted.

**Comment by andrejpavlovic** [comment]
Issue has become stale. Please reopen if further assistance needed.
